### ISSUE TITLE
PeoplePicker control of Microsoft.Toolkit.Graph.Controls Asking for singing again if already & Sing out automatically after adding new event

### ISSUE THREAD

**Issue by vikanirav** [microsoftgraph/msgraph-training-uwp#42] opened 2022-04-23 08:10 UTC
**Where did you get the code?**
- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
After sign in into the given demo application, I was trying to add new event. It is asking for sign in again when I try to search event Attendee by their name in PeoplePicker control. 

**To Reproduce**
Issue 1:
      1. Open the application from visual studio
      2. sign in into the application & go to the NewEvent Page
      3. Try to search by name in Attendee Textbox(PeoplePicker control) : Use name of already sign in user 
      4. After sign in again from sign in window, sign in window will not close. you need to close manually.
      5. Create event & after creating it will sign out you from application
      6. go to the Calendar page, it will ask for sign in again

Issue 2:
      1. Open the application from visual studio
      2. sign in into the application & go to the NewEvent Page
      3. Try to search by name in Attendee Textbox(PeoplePicker control) : Use different name of user by which you are not sign in
      4. After sign in again from sign in window, sign in window will hang.
      5. go to the Calendar page, it will ask for sign in again

**Expected behavior**
1. After sign in into the application, user try to search user by their name in Attendee Textbox(PeoplePicker control), I should not ask for sign in again.
2. If user try to search by different user name, sign in window should not hang

**Screenshots**
After search user by different name than already sign in, the app just hangs indefinitely and a little blue flashing dot appears in the upper left hand corner. (See attached image for issue 2)
![image](https://user-images.githubusercontent.com/64262100/164885982-1f7ac20f-51ae-46b9-8acc-ceb198cc63b8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: N/A

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

**Additional context**
Visual studio 22

**Comment by jasonjoh** [comment] 2022-04-28 19:37
It looks like there's a missing permission scope that the people picker needs: `People.Read`. If you add that scope to your OAuth.resw does it help?

I would also recommend investigating replacing the Microsoft.Toolkit.Graph.Controls (which is deprecated) with their recommendation: CommunityToolkit.Graph.Uwp. I'm planning to update this sample to use it when I can.

**Comment by vikanirav** [comment] 2022-04-29 16:57
Hello @jasonjoh,
Thank you for replying. 

I added your suggested permission and people picker is working fine now. But I am getting inconsistence sign in behavior in the application. It is asking me for sign in again even though I already signed in into the application[See attached screenshot].

I also tried with "CommunityToolkit.Graph.Uwp" nuget packages. But I am getting singout state after sign in. Please check this issue. [CommunityToolkit.Graph.Uwp issue](https://github.com/CommunityToolkit/Graph-Controls/issues/187)

![image](https://user-images.githubusercontent.com/64262100/165988607-ae168140-f8d6-461c-bef3-e39172586f8e.png)

**Comment by jasonjoh** [comment] 2022-10-05 18:27
Closing as we've updated to use the CommunityToolkit.Graph.Uwp packages, and I cannot reproduce the second issue mentioned.

**Closed by jasonjoh** 2022-10-05 18:27 UTC
Labels: cannot repro
